# Generated by Django 5.2.1 on 2025-06-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
