# Generated by Django 5.2.1 on 2025-06-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_film_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
