# Generated by Django 5.2.1 on 2025-06-09 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstreamingservice',
            name='streaming_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.streamingservice'),
        ),
        migrations.AddField(
            model_name='userstreamingservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='streaming_services',
            field=models.ManyToManyField(related_name='users', through='authentication.UserStreamingService', to='movie.streamingservice'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='userstreamingservice',
            unique_together={('user', 'streaming_service')},
        ),
    ]
