name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: movie_picker
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 movie_picker
      - name: Copy .env.example to .env
        run: cp .env.example .env
      - name: Set up test environment variables
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "DB_NAME=movie_picker" >> .env
          echo "DB_ENGINE=django.db.backends.postgresql" >> .env
      - name: Run migrations
        run: |
          python movie_picker/manage.py migrate
      - name: Run tests
        run: |
          python movie_picker/manage.py test
